# Bash aliases
#
alias ll='ls -loh --group-directories-first'
alias la='ls -A --group-directories-first'
alias lal='ls -Al'
alias lgd='ls --group-directories-first'
alias lagd='ls -A --group-directories-first'
alias lh='ls -sh'
alias llh='ls -lh'
alias lah='ls -Ash'
alias lalh='ls -Alh'
alias duh='du -sh'
alias dfh='df -h'
alias :q='exit'

# http://eriwen.com/productivity/aliases-and-functions/
alias ..='cd ..'
alias ...='cd ../..'
alias c='cd'
alias f='find'
alias g='grep'
alias h='history'
alias o='popd'
alias p='pushd'
alias d='dirs'
alias please='sudo'

# Git aliases
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gp='git pull'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gr='git remote -v'
alias gits='git svn'

alias got='git '
alias get='git '
